### ISSUE TITLE
markdown table doesn't display cell borders

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1421]
- We should check the style so it supports the expected behavior
- Provide a way to over-ride the markdown table styling
- Create a wiki page on how to over-ride the styling. Based on my experience, chaise looks for styling under /assets/styles/chaise.css. You can check with @RFSH on the detail. 

Also, the markdown rendering of preview and the actual render in the app looks different.

**Comment by RFSH** [comment]
If we want our markdown to look like github markdown by default, we can replicate the same css styles that github is applying. We don't need to figure out the css ourself, we can use [this](https://github.com/sindresorhus/github-markdown-css/blob/gh-pages/github-markdown.css) one. In this css files they are using `markdown-body` class which we should just change it to `markdown-container` and then use it.

For custom css for deployment, it's a chaise-config attribute (`customCSS`).

**Comment by amitjha21** [comment]
Added `gihub` css in our repo.
Here is the demo link:
https://dev.isrd.isi.edu/~amit/md/record/#1/isa:dataset/id=269

**Comment by amitjha21** [comment]
I have tested above link with markdown entries and also with custom CSS in assets/css/chaise.css.
It works as expected and provides a way to override styling by changing classes in custom CSS.

However, adding styles through specific classes that applies only during rendering in `record` app and not during preview in `recordedit` app (or vice versa) will cause expected differences in appearance (as can be seen in current dev rbk portal).

**Comment by RFSH** [comment]
What are those specific styles that we are applying just for `record` app? Can't they be just based on `markdown-container` so it would work on any apps?

**Comment by amitjha21** [comment]
We do not have anything app specific. It is all on `.markdown-container`.

**Comment by RFSH** [comment]
You said "adding styles through specific classes that applies only during rendering in record app and not during preview in recordedit app (or vice versa) will cause expected differences in appearance (as can be seen in current dev rbk portal)", I'm just asking what are these styles that we are applying only to record app in rbk?

**Comment by amitjha21** [comment]
Here are some  examples I found in rbk portal custom CSS:
``` css
#tblRecord td.entity-value table {
  
}

#tblRecord td.entity-value table>tbody>tr>td, #tblRecord td.entity-value table>tbody>tr>th, #tblRecord td.entity-value table>tfoot>tr>td, #tblRecord td.entity-value table>tfoot>tr>th, #tblRecord td.entity-value table>thead>tr>td, #tblRecord td.entity-value table>thead>tr>th {
    padding: 8px;
    line-height: 1.42857143;
    vertical-align: top;
    border-top: 1px solid #ddd;
}

#tblRecord td.entity-value table>caption+thead>tr:first-child>td, #tblRecord td.entity-value table>caption+thead>tr:first-child>th, #tblRecord td.entity-value table>colgroup+thead>tr:first-child>td, #tblRecord td.entity-value table>colgroup+thead>tr:first-child>th, #tblRecord td.entity-value table>thead:first-child>tr:first-child>td, #tblRecord td.entity-value table>thead:first-child>tr:first-child>th {
    border-top: 0;
}

#tblRecord td.entity-value table>thead>tr>th, #tblRecord td.entity-value table>tbody>tr>th, #tblRecord td.entity-value table>tfoot>tr>th, #tblRecord td.entity-value table>thead>tr>td, #tblRecord td.entity-value table>tbody>tr>td, #tblRecord td.entity-value table>tfoot>tr>td {
    border-top: none;
    border-bottom: 1px solid #ddd;
    max-width: 500px;
    word-wrap: break-word;
}

#tblRecord td.entity-value table>thead>tr>th {
    vertical-align: bottom;
    border-bottom: 2px solid #ddd;
}
```
If these classes are removed from `/assets/styles/chaise.css` then both preview and actual rendering are   same.
