### ISSUE TITLE
Multi-line tooltips

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1786]
Currently the tooltips are displayed in a single line as they ignore the `\n`s that might exist in the tooltip. So it's not possible for data-modelers to show the tooltips in multiple lines.

Adding the following css rule will fix this:
```css
.tooltip-inner {
    white-space:pre-wrap;
}
```

But I'm not sure how it will affect the current tooltips and test cases.
