### ISSUE TITLE
Hiding Entity Key column - text not wrapping

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1993]
In RBK, there is a custom style written to hide the `enitity-key` for one of the columns in the `visible-columns` section. We should be wrapping the text properly when hiding the `entity-key` column but the `entity-value` remains.

The following styles are currently being applied to [this page](https://dev.rebuildingakidney.org/chaise/record/#2/RNASeq:Study/RID=16-1YZM):
```CSS
/* Study:Cellbrowser_URI : suppress column header */
.r_s_RNASeq.r_t_Study #row-Cellbrowser_URI .entity-key {
    display: none;
}

/* Study:Cellbrowser_URI: indent iframe */
.r_s_RNASeq.r_t_Study #row-Cellbrowser_URI .entity-value {
  padding-left: 40px;

  /* temporary solution that will fix the wrapping of iframe caption
   * This is caused because we're setting width for the firt column,
   * and by hiding the header cell, the data cell will be treated as first column by HTML.
   */
  white-space: nowrap;
}
```

[Another page](https://dev.rebuildingakidney.org/chaise/record/#2/Gene_Expression:Image/RID=14-47WJ) with the following styles:
```CSS
/* suppress column header */
.r_s_Gene_Expression.r_t_Image #row-uri .entity-key {
    display: none;
}
/* indent iframe */

.r_s_Gene_Expression.r_t_Image #row-uri .entity-value {
  padding-left: 40px;
}
```

[And a 3rd page](https://dev.rebuildingakidney.org/chaise/record/#2/Gene_Expression:Image_Annotation/RID=17-6VTW) with the following styles:
```CSS
/* ------ Gene Expression: Image_Annotation_File ----------- */
/* suppress column header */
.r_s_Gene_Expression.r_t_Image_Annotation_File #row-\$Preview .entity-key {
  display: none;
}

.r_s_Gene_Expression.r_t_Image_Annotation_File #row-\$Preview .entity-value {
  padding-left: 40px;
}
```
