### ISSUE TITLE
Add a custom banner to chaise pages

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2126]
In some cases we want to show a banner in all chaise pages. In CFDE we've solved this by adding the following CSS rule

```css
navbar header.row::before {
    content: "BANNER CONTENT";
    height: 30px;
    background-color: #447e71;
    color: white;
    padding: 10px 0px;
    width: 100%;
    text-align: center;
}
```

Which will display `BANNER CONTENT` on top of all the chaise pages above the navbar. With this approach we can only show text contents and it cannot have any HTML tags. So for instance you cannot have a link in its content.

Therefore, we should add a proper chaise-config property that allows data-modelers to define a banner. This banner should support `markdown_pattern` so they can have links or any other HTML elements. The following is how the proposed property should like like:
```javascript
{
  "navbarBanner": {
    "name": "",
    "markdown_pattern": "",
    "dismissible": false, // (optional)
    "position": "top", // (optional, other acceptable value: "bottom") 
  }
}
```
I think this should be an object so we can add optional properties to allow more customization. The extra optional properties that we discussed are:

- `"dismissible": true` should add a "x" to the banner that allows users to dismiss it. If user dismisses the alert, we're not going to remember this decision and they're going to see the banner once they reload the page. Later we might want to make this more complicated like the session expire alert. 

- By default we're going to add the banner on top of the navbar. We could define a `"position": "bottom"` to add the banner below the navbar.
