### ISSUE TITLE
Multi-row recordset table headings 

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2229]
In recordset tables, we've intentionally ensured the column names in the table header stay in one line. While this helps with alignment and consistency, it's not desirable in some cases. For example, if the column name is longer than the maximum length of the column values, the whole table's column will be wide, and we will waste a lot of space:

![Screen Shot 2022-09-06 at 9 42 43 AM](https://user-images.githubusercontent.com/2129750/188690942-9deb9730-690f-4561-ac99-b4ca072fff97.png)

Therefore we decided to apply some custom CSS to force some column headers to appear in two lines:
![Screen Shot 2022-09-06 at 9 37 24 AM](https://user-images.githubusercontent.com/2129750/188691027-947b6eaf-fbde-4130-85f9-024ca7d3db8b.png)

To do so, we applied the following CSS rules:

```css
/* make sure the header appears in the first line */
.s_schema.t_table th {
    vertical-align: top;
}
/* move the sort icon to be aligned with the first line */
.s_schema.t_table th .table-heading-icons {
    top: 8px;
}

.s_scema.t_table th.c_column_w_long_name {
    /* ensure breaking of the content in multiple lines*/
    white-space: inherit !important;
    /* ensure two lines (both rules needed): */
    min-width: 90px;
    width: 90px;
}
```
As you can see, we have to manually set the width to ensure the name is broken in the specific character we see fit. While this works in this particular scenario, we might want to develop a more general solution that doesn't require handcrafting. We could potentially implement this as a built-in feature that data-modelers can turn on.
